<div class="post type-photo">
            <div class="post-inner" style="display: block; ">
              <div class="post-list-cover" style="overflow: hidden; ">
              
              <img src="<!img>" alt="Girl" style="display: inline; width: 209px; margin-top: -25px; ">
              </div>
              <div class="post-list-link" style="display: none; ">
              <div class="post-list-cover-hover">
              </div>
              
                <a class="post-link" title="<!link>" href="<!link>">
                <!link>
                </a>
              </div>
            </div>
</div>